flower_workshop/bouquets/urls.py
from django.urls import path

from .views import card, catalog, quiz_delivery, quiz_payment, result

app_name = 'bouquets'

urlpatterns = [
    path('catalog/', catalog, name='catalog'),
    path('result/', result, name='result'),
    path('quiz/drlivery-step/', quiz_delivery, name='quiz_delivery_step'),
    path('quiz/payment-step/', quiz_payment, name='quiz_payment_step'),
    path('card/<int:pk>/', card, name='card'),
]

flower_workshop/flower_workshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('order/', include('orders.urls')),
    path('bouquets/', include('bouquets.urls')),
    path('consultation/', include('consultation.urls'))
]

if settings.DEBUG:
    urlpatterns += (
        path("403/", default_views.permission_denied, kwargs={"exception": Exception("У вас нет доступа.")}),
        path("404/", default_views.page_not_found, kwargs={"exception": Exception("Страница не найдена.")}),
        path("500/", default_views.server_error),
    )
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flower_workshop/home/urls.py
from .views import index

from django.urls import path

urlpatterns = [
    path('', index, name='home')
]

flower_workshop/bouquets/models.py
from decimal import Decimal

from django.db import models


class Event(models.Model):
    name = models.CharField('Название события', max_length=100, blank=True, db_index=True)

    class Meta:
        verbose_name = 'Событие'
        verbose_name_plural = 'События'

    def __str__(self):
        return self.name


class Flower(models.Model):
    name = models.CharField('Цветок', max_length=100, blank=True, db_index=True)

    class Meta:
        verbose_name = 'Цветок'
        verbose_name_plural = 'Виды цветов'

    def __str__(self):
        return self.name


class BouquetFlower(models.Model):
    flower = models.ForeignKey(Flower, on_delete=models.PROTECT, verbose_name='Цветов')
    quantity = models.PositiveSmallIntegerField('Количество')
    bouquet = models.ForeignKey(
        'bouquets.Bouquet',
        on_delete=models.PROTECT,
        verbose_name='букет',
        related_name='flowers',
    )

    class Meta:
        verbose_name = 'Цветок в букете'
        verbose_name_plural = 'Цветы в букете'

    def __str__(self):
        return '{0} - {1}'.format(self.flower, self.quantity)


class Bouquet(models.Model):
    name = models.CharField('Название', max_length=100, blank=True, db_index=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, default=Decimal('0'))
    image = models.ImageField(upload_to='bouquets_images', blank=True, null=True)
    description = models.TextField('Описание', blank=True)
    events = models.ManyToManyField(Event, verbose_name='События')
    recommended = models.BooleanField('В рекомендованных', default=False, db_index=True)

    class Meta:
        verbose_name = 'Букет'
        verbose_name_plural = 'Букеты'

    def __str__(self):
        return '{0} - {1}'.format(self.name, self.price)

flower_workshop/bouquets/views.py
import random
from decimal import Decimal

from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404
from django.shortcuts import render

from .models import Bouquet, Event

TOTAL_STEPS = 2


def catalog(request):
    bouquets = Bouquet.objects.all()
    paginator = Paginator(bouquets, 3)
    page_obj = paginator.get_page(request.GET.get("page", 1))
    if request.htmx:
        return render(request, 'bouquets/components/catalog_page.html', context={'page_obj': page_obj})
    return render(request, 'bouquets/catalog.html', context={'page_obj': page_obj})


def card(request, pk):
    return render(request, 'bouquets/card.html', context={'bouquet': get_object_or_404(Bouquet, pk=pk)})


def result(request):
    event_id = request.GET.get('event_id')
    price_from = Decimal(request.GET.get('price_from', '0'))
    price_to = Decimal(request.GET.get('price_to', '999999'))
    bouquets = Bouquet.objects.filter(price__gte=price_from, price__lte=price_to)
    if event_id and event_id != 'None':
        events = [get_object_or_404(Event, pk=event_id), ]
        bouquets.filter(events__in=events)

    if bouquets:
        context = {
            "bouquet": random.choice(list(bouquets)),
            "title": "Мы подобрали специально для Вас",
        }
    else:
        context = {
            "bouquet": None,
            "title": "К сожалению, по вашему запросу ничего не нашлось",
        }
    return render(request, 'bouquets/result.html', context)


def quiz_delivery(request):
    return render(
        request,
        'bouquets/quiz.html',
        context={
            'step': 1,
            'total_steps': TOTAL_STEPS,
            'events': Event.objects.all(),
        },
    )


def quiz_payment(request):
    return render(
        request,
        'bouquets/quiz-step.html',
        context={
            'step': 2,
            'total_steps': TOTAL_STEPS,
            'event_id': request.GET.get('event_id'),
        },
    )

flower_workshop/templates/bouquets/card.html
{% extends 'base.html' %}
{% load static humanize %}
{% block title %}{{ bouquet.name }}{% endblock %}
{% block content %}
	<section id="card">
		<div class="container">
			<div class="card ficb">
				<div class="card__block card__block_first">
					<img src="{{ bouquet.image.url }}" alt="{{ bouquet.name }}" class="card__img">
				</div>
				<div class="card__block card__block_sec">
					<div class="title">{{ bouquet.name }}</div>
					<div class="card__block_price">{{ bouquet.price|floatformat|intcomma }} руб</div>
					<div class="card__elems ">
						<span class="card__elems_intro">Состав</span>
						<div class="card__items">
                            {% for bouquet_flower in bouquet.flowers.all %}
                                <span class="card_items_intro">
                                    {{ bouquet_flower.flower }} - {{ bouquet_flower.quantity }} шт.
                                </span>
                            {% endfor %}
						</div>
					</div>
					<button class="btn largeBtn card__btn" onclick='goto(`{% url 'order' %}?bouquet_id={{ bouquet.pk }}`)'>
                        Заказать букет
                    </button>
				</div>
			</div>
		</div>
	</section>
	<section id="consultation">
        <div class="container">
            <div class="consultation">
                <div class="title consultation__title">Оставьте заявку на консультацию</div>
                {% include 'consultation/components/consultation_form.html' %}
            </div>
        </div>
    </section>
{% endblock content %}

flower_workshop/templates/bouquets/catalog.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Все букеты{% endblock %}
{% block content %}
	<section id="catalog">
		<div class="container p100">
			<div class="catalog">
				<div class="title">Все букеты</div>
				<div class="catalog__block" hx-trigger="load" hx-post="{% url 'bouquets:catalog' %}" hx-swap="innerHTML"></div>
                <button class="btn largeBtn catalog__btn" id="next_btn">Загрузка...</button>
			</div>
		</div>
	</section>
	<section id="consultation">
        <div class="container">
            <div class="consultation">
                <div class="title consultation__title">Оставьте заявку на консультацию</div>
                {% include 'consultation/components/consultation_form.html' %}
            </div>
        </div>
    </section>
{% endblock content %}

flower_workshop/templates/bouquets/quiz-step.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Подбор букета{% endblock %}
{% block content %}
	<section id="quiz">
		<div class="container">
			<div class="quiz">
				<div class="quiz__back ">
					<a href="#" class="quiz__back_link fic"><img src="{% static 'img/arrow-left.svg' %}" alt="arrow-left" class="arrowLeft">
					<span class="quiz__back_intro" onclick='goto(`{% url "bouquets:quiz_delivery_step" %}`)'>Назад</span></a>
				</div>
				<div class="quiz__block">
					<h1 class="quiz__title">На какой бюджет рассчитываете?</h1>
					<div class="quiz__elems fic">
						<button class="quiz__elem" onclick='goto(`{% url 'bouquets:result' %}?event_id={{ event_id }}&price_to=1000`)'>До 1 000 руб</button>
						<button class="quiz__elem" onclick='goto(`{% url 'bouquets:result' %}?event_id={{ event_id }}&price_from=1000&price_to=5000`)'>1 000 - 5 000 руб</button>
						<button class="quiz__elem" onclick='goto(`{% url 'bouquets:result' %}?event_id={{ event_id }}&price_from=5000`)'>от 5 000 руб</button>
						<button class="quiz__elem" onclick='goto(`{% url 'bouquets:result' %}?event_id={{ event_id }}`)'>Не имеет значения</button>
					</div>
					{% include 'bouquets/components/quiz_progress.html' with step=step total_steps=total_steps progress="100%" only %}
				</div>
			</div>
		</div>
	</section>
{% endblock content %}

flower_workshop/templates/bouquets/quiz.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Подбор букета{% endblock %}
{% block content %}
	<section id="quiz">
		<div class="container">
			<div class="quiz">
				<div class="quiz__back ">
					<a href="#" class="quiz__back_link fic"><img src="{% static 'img/arrow-left.svg' %}" alt="arrow-left" class="arrowLeft">
					<span class="quiz__back_intro" onclick='goto("/")'>Назад</span></a>
				</div>
				<div class="quiz__block">
					<h1 class="quiz__title">К какому событию нужен букет?</h1>
					<div class="quiz__elems fic">
                        <button class="quiz__elem" onclick='goto(`{% url 'bouquets:quiz_payment_step' %}`)'>Любой</button>
                        {% for event in events %}
                            <button class="quiz__elem" onclick='goto(`{% url 'bouquets:quiz_payment_step' %}?event_id={{ event.pk }}`)'>{{ event.name }}</button>
                        {% endfor %}
					</div>
                    {% include 'bouquets/components/quiz_progress.html' with step=step total_steps=total_steps progress="2%" only %}
				</div>
			</div>
		</div>
	</section>
{% endblock content %}

flower_workshop/templates/bouquets/result.html
{% extends 'base.html' %}
{% load static humanize %}
{% block title %}Подбор букета{% endblock %}
{% block content %}
	<section id="result">
		<div class="container">
			<div class="result p100">
				<div class="title">{{ title }}</div>
				<div class="result__block ficb">
                    {% if bouquet %}
                        <div class="result__elems">
                            <div class="card__elems ">
                                <span class="card__elems_intro">Описание:</span>
                                <div class="card__items">
                                    <p class="card__items_text card__items_text__first">
                                        {{ bouquet.description }}
                                    </p>
                                </div>
                            </div>
                            <div class="card__elems ">
                                <span class="card__elems_intro">Состав:</span>
                                <div class="card__items">
                                    <p class="card__items_text card__items_text__first">
                                         {% for bouquet_flower in bouquet.flowers.all %}
                                            {{ bouquet_flower.flower }} {{ bouquet_flower.quantity }} шт.<br>
                                        {% endfor %}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <img src="{{ bouquet.image.url }}" alt="result Img" class="result__block_img">
                    {% endif %}
					<div class="result__items">
                        {% if bouquet %}
                            <div class="title result__items_title">{{ bouquet.name }}</div>
                            <div class="result__items_price">{{ bouquet.price|floatformat|intcomma }} руб</div>
                            <button class="btn result__items_btn" onclick='goto(`{% url 'order' %}?bouquet_id={{ bouquet.pk }}`)'>Заказать букет</button>
                            <hr class="result__items_line" />
                            <div class="result__items_intro">Хотите что-то более специальное?</div>
                        {% else %}
                            <div class="result__items_intro">Попробуйте что-нибудь другое:</div>
                        {% endif %}
						<div class="result__items_block">
							<button class="btn largeBtn result__items_block__btn" onclick='goto(`{% url 'bouquets:catalog' %}`)'>Смотреть всю коллекцию</button>
							<button class="btn largeBtn result__items_block__btn" onclick='goto(`/#consultation`)'>Заказать консультацию</button>
						</div>
					</div>
				</div>	
			</div>
		</div>
	</section>
	<section id="contacts">
		<div class="container">
			<div class="contacts">
				<div class="title">Как нас найти</div>
				<div class="contacts__elems ficb">
					<div class="contacts__block">
						<div class="contacts__block_item ficc">
							<div class="contacts__block_intro">ул. Пушкинская, 69</div>
							<a href="tel:89111744460" class="contacts__block_tel">8 (911) 17 44 460</a>
						</div>
						<div class="contacts__block_item ficc">
							<div class="contacts__block_intro">ул. Пушкинская, 69</div>
							<a href="tel:89111744460" class="contacts__block_tel">8 (911) 17 44 460</a>
						</div>
						<div class="contacts__block_item ficc">
							<div class="contacts__block_intro">ул. Пушкинская, 69</div>
							<a href="tel:89111744460" class="contacts__block_tel">8 (911) 17 44 460</a>
						</div>
					</div>
					<img src="{% static 'img/contactsImg.jpg' %}" alt="contactsImg" class="contacts__img">
					<div class="contacts__map">
						<script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Af39d7a7f1829359b6ffe21ab6356fcaeace17d528d6522dba8772f885c8b1a7d&amp;width=398&amp;height=316&amp;lang=ru_RU&amp;scroll=true"></script>
					</div>					
				</div>
				<button class="btn contacts__btn">Заказать доставку</button>
			</div>
		</div>
	</section>
	<section id="consultation">
        <div class="container">
            <div class="consultation">
                <div class="title consultation__title">Оставьте заявку на консультацию</div>
                {% include 'consultation/components/consultation_form.html' %}
            </div>
        </div>
    </section>
{% endblock content %}