flower_workshop/bouquets/urls.py
from django.urls import path

from .views import card, catalog, quiz_delivery, quiz_payment, result

app_name = 'bouquets'

urlpatterns = [
    path('catalog/', catalog, name='catalog'),
    path('result/', result, name='result'),
    path('quiz/drlivery-step/', quiz_delivery, name='quiz_delivery_step'),
    path('quiz/payment-step/', quiz_payment, name='quiz_payment_step'),
    path('card/<int:pk>/', card, name='card'),
]

flower_workshop/flower_workshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('order/', include('orders.urls')),
    path('bouquets/', include('bouquets.urls')),
    path('consultation/', include('consultation.urls'))
]

if settings.DEBUG:
    urlpatterns += (
        path("403/", default_views.permission_denied, kwargs={"exception": Exception("У вас нет доступа.")}),
        path("404/", default_views.page_not_found, kwargs={"exception": Exception("Страница не найдена.")}),
        path("500/", default_views.server_error),
    )
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flower_workshop/home/urls.py
from .views import index

from django.urls import path

urlpatterns = [
    path('', index, name='home')
]

flower_workshop/bouquets/models.py
from decimal import Decimal

from django.db import models


class Event(models.Model):
    name = models.CharField('Название события', max_length=100, blank=True, db_index=True)

    class Meta:
        verbose_name = 'Событие'
        verbose_name_plural = 'События'

    def __str__(self):
        return self.name


class Flower(models.Model):
    name = models.CharField('Цветок', max_length=100, blank=True, db_index=True)

    class Meta:
        verbose_name = 'Цветок'
        verbose_name_plural = 'Виды цветов'

    def __str__(self):
        return self.name


class BouquetFlower(models.Model):
    flower = models.ForeignKey(Flower, on_delete=models.PROTECT, verbose_name='Цветов')
    quantity = models.PositiveSmallIntegerField('Количество')
    bouquet = models.ForeignKey(
        'bouquets.Bouquet',
        on_delete=models.PROTECT,
        verbose_name='букет',
        related_name='flowers',
    )

    class Meta:
        verbose_name = 'Цветок в букете'
        verbose_name_plural = 'Цветы в букете'

    def __str__(self):
        return '{0} - {1}'.format(self.flower, self.quantity)


class Bouquet(models.Model):
    name = models.CharField('Название', max_length=100, blank=True, db_index=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, default=Decimal('0'))
    image = models.ImageField(upload_to='bouquets_images', blank=True, null=True)
    description = models.TextField('Описание', blank=True)
    events = models.ManyToManyField(Event, verbose_name='События')
    recommended = models.BooleanField('В рекомендованных', default=False, db_index=True)

    class Meta:
        verbose_name = 'Букет'
        verbose_name_plural = 'Букеты'

    def __str__(self):
        return '{0} - {1}'.format(self.name, self.price)

flower_workshop/bouquets/views.py
import random
from decimal import Decimal

from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404
from django.shortcuts import render

from .models import Bouquet, Event

TOTAL_STEPS = 2


def catalog(request):
    bouquets = Bouquet.objects.all()
    paginator = Paginator(bouquets, 3)
    page_obj = paginator.get_page(request.GET.get("page", 1))
    if request.htmx:
        return render(request, 'bouquets/components/catalog_page.html', context={'page_obj': page_obj})
    return render(request, 'bouquets/catalog.html', context={'page_obj': page_obj})


def card(request, pk):
    return render(request, 'bouquets/card.html', context={'bouquet': get_object_or_404(Bouquet, pk=pk)})


def result(request):
    event_id = request.GET.get('event_id')
    price_from = Decimal(request.GET.get('price_from', '0'))
    price_to = Decimal(request.GET.get('price_to', '999999'))
    bouquets = Bouquet.objects.filter(price__gte=price_from, price__lte=price_to)
    if event_id and event_id != 'None':
        events = [get_object_or_404(Event, pk=event_id), ]
        bouquets.filter(events__in=events)

    if bouquets:
        context = {
            "bouquet": random.choice(list(bouquets)),
            "title": "Мы подобрали специально для Вас",
        }
    else:
        context = {
            "bouquet": None,
            "title": "К сожалению, по вашему запросу ничего не нашлось",
        }
    return render(request, 'bouquets/result.html', context)


def quiz_delivery(request):
    return render(
        request,
        'bouquets/quiz.html',
        context={
            'step': 1,
            'total_steps': TOTAL_STEPS,
            'events': Event.objects.all(),
        },
    )


def quiz_payment(request):
    return render(
        request,
        'bouquets/quiz-step.html',
        context={
            'step': 2,
            'total_steps': TOTAL_STEPS,
            'event_id': request.GET.get('event_id'),
        },
    )

flower_workshop/templates/bouquets/components/bouquet_card.html
{% load static humanize %}
<div class="recommended__block recommended__block_first"
     onclick='goto(`{% url 'bouquets:card' pk=bouquet.pk %}`)'
     {% if bouquet.image %}
        style="background: url({{ bouquet.image.url }}) no-repeat center bottom / cover;"
     {% endif %}
>
    <div class="recommended__block_elems ficb">
        <span class="recommended__block_intro">{{ bouquet.name }}</span>
        <span class="recommended__block_price">{{ bouquet.price|floatformat|intcomma }} руб</span>
    </div>
</div>

flower_workshop/templates/bouquets/components/catalog_page.html
<div class="recommended__elems ficb recommended__elems_first">
    {% for bouquet in page_obj %}
        {% include 'bouquets/components/bouquet_card.html' with bouquet=bouquet only %}
    {% endfor %}
</div>
{% include 'bouquets/components/more_btn.html' %}

flower_workshop/templates/bouquets/components/more_btn.html
{% if page_obj.has_next %}
    <button id="next_btn"
            class="btn largeBtn catalog__btn"
            hx-get="{% url 'bouquets:catalog' %}?page={{ page_obj.next_page_number }}"
            hx-swap-oob="outerHTML"
            hx-target=".catalog__block"
            hx-swap="beforeend"
    >
        Показать ещё
    </button>
{% else %}
    <button hx-swap-oob="delete" id="next_btn"></button>
{% endif %}

flower_workshop/templates/bouquets/components/quiz_progress.html
<div class="quiz__progress">
    <div class="quiz__progress_step">
        <span class="quiz__progress_num">{{ step }}</span>
        <span class="quiz__progress_in"> шаг из </span>
        <span class="quiz__progress_num">{{ total_steps }}</span>
    </div>
    <div class="quiz__progress_line">
        <div class="quiz__progress_lineActive" style="width: {{ progress }}"></div>
    </div>
</div>

flower_workshop/templates/bouquets/components/recommended_card.html
 {% load static humanize %}

<div class="recommended__block recommended__block_first"
     {% if bouquet.image %}
        style="background: url({{ bouquet.image.url }}) no-repeat center bottom / cover;"
     {% endif %}
>
    <div class="recommended__block_elems ficb">
        <span class="recommended__block_intro">{{ bouquet.name }}</span>
        <span class="recommended__block_price">{{ bouquet.price|floatformat|intcomma }} руб</span>
    </div>
</div>