flower_workshop/consultation/urls.py
from .views import consultation, ConsultationFormView

from django.urls import path

app_name = "consultation"

urlpatterns = [
    path('', consultation, name='consultation'),
    path('submit/', ConsultationFormView.as_view(), name="submit_form"),
]

flower_workshop/flower_workshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('order/', include('orders.urls')),
    path('bouquets/', include('bouquets.urls')),
    path('consultation/', include('consultation.urls'))
]

if settings.DEBUG:
    urlpatterns += (
        path("403/", default_views.permission_denied, kwargs={"exception": Exception("У вас нет доступа.")}),
        path("404/", default_views.page_not_found, kwargs={"exception": Exception("Страница не найдена.")}),
        path("500/", default_views.server_error),
    )
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flower_workshop/home/urls.py
from .views import index

from django.urls import path

urlpatterns = [
    path('', index, name='home')
]

flower_workshop/consultation/models.py
from django.core.validators import MinLengthValidator
from django.db import models
from django.conf import settings
from phonenumber_field.modelfields import PhoneNumberField
from phonenumber_field.validators import PhoneNumber

class Consultation(models.Model):
    class Statuses(models.TextChoices):
        NOT_PROCESSED = 'NP', 'Не обработана'
        DENIED = 'DN', 'Отказ'
        ORDER = 'OR', 'Сделан заказ'

    florist = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Флорист'
    )
    name = models.CharField(
        'Имя',
        max_length=100,
        db_index=True,
        validators=[MinLengthValidator(3)],
    )
    phone = PhoneNumberField('Телефон', db_index=True)
    status = models.CharField(
        'Статус', max_length=2, choices=Statuses.choices, default=Statuses.NOT_PROCESSED, db_index=True
    )

    class Meta:
        verbose_name = 'Заявка на консультацию'
        verbose_name_plural = 'Заявки на консультацию'

    def __str__(self):
        return '{0} - {1} - {2}'.format(self.name, self.phone, self.status)

flower_workshop/consultation/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from phonenumber_field.formfields import PhoneNumberField

from consultation.models import Consultation


class CounsultationForm(ModelForm):
    phone = PhoneNumberField()
    phone.error_messages['invalid'] = "Введите корректный номер телефона, например: +7 (933) 933-33-33"
    class Meta:
        model = Consultation
        fields = ["name", "phone"]

flower_workshop/consultation/views.py
from django.shortcuts import render
from django.views import View

from .forms import CounsultationForm
from django.http import Http404

def consultation(request):
    return render(request, 'consultation/consultation.html', context={})


class ConsultationFormView(View):
    def get(self):
        raise Http404
    def post(self, request):
        if request.htmx:
            form = CounsultationForm(request.POST)
            if form.is_valid():
                form.save()
                return render(request, 'consultation/components/consultation_form_success.html', context={'form': form})
            return render(request, 'consultation/components/consultation_form.html', context={'form': form})
        raise Http404

flower_workshop/templates/consultation/components/consultation_form.html
{% load static %}
<form hx-post="{% url 'consultation:submit_form' %}" class="consultation__form" hx-swap="outerHTML">
    <input type="text" name="name" class="consultation__form_input" placeholder="Введите Имя" required>

    <input id="phone_input" type="text" name="phone" class="consultation__form_input" placeholder="+ 7 (999) 000 00 00"
           required>
    <button type="submit" class="consultation__form_btn">Отправить</button>
    {% if form.errors %}
        <div class="errors"
             style="padding: 1em 0; color: red; font-weight: bold;"
        >
            {{ form.non_field_errors }}
            {{ form.name.errors }}
            {{ form.phone.errors }}
        </div>
    {% endif %}
</form>
<script>
    IMask(
        document.getElementById('phone_input'),
        {mask: '+{7} (000) 000-00-00'}
    );
</script>

flower_workshop/templates/consultation/components/consultation_form_success.html
<div class="title consultation__title">Мы перезвоним вам в течение 15 минут</div>