flower_workshop/bouquets/urls.py
from django.urls import path

from .views import card, catalog, quiz_delivery, quiz_payment, result

app_name = 'bouquets'

urlpatterns = [
    path('catalog/', catalog, name='catalog'),
    path('result/', result, name='result'),
    path('quiz/drlivery-step/', quiz_delivery, name='quiz_delivery_step'),
    path('quiz/payment-step/', quiz_payment, name='quiz_payment_step'),
    path('card/<int:pk>/', card, name='card'),
]

flower_workshop/flower_workshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('order/', include('orders.urls')),
    path('bouquets/', include('bouquets.urls')),
    path('consultation/', include('consultation.urls'))
]

if settings.DEBUG:
    urlpatterns += (
        path("403/", default_views.permission_denied, kwargs={"exception": Exception("У вас нет доступа.")}),
        path("404/", default_views.page_not_found, kwargs={"exception": Exception("Страница не найдена.")}),
        path("500/", default_views.server_error),
    )
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flower_workshop/home/urls.py
from .views import index

from django.urls import path

urlpatterns = [
    path('', index, name='home')
]

flower_workshop/orders/urls.py
from .views import create_order, order_step, my_order

from django.urls import path

urlpatterns = [
    path('', create_order, name='order'),
    path('step/', order_step, name='order-step'),
    path('my-order/<int:pk>/', my_order, name='my_order'),
]

flower_workshop/orders/models.py
from django.conf import settings
from django.db import models
from model_utils.models import TimeStampedModel
from phonenumber_field.modelfields import PhoneNumberField

from bouquets.models import Bouquet


# Create your models here.
class StatusOrder(models.TextChoices):
    unprocessed = 'UP', 'Необработанный заказ',
    in_work = 'IW', 'Собирается флористом'
    delivery = 'DL', 'Передан курьеру'
    completed = 'CP', 'Заказ завершён'


class IntervalOrder(models.TextChoices):
    first = 'FRS', 'Как можно скорее'
    two = 'TW', 'с 10:00 до 12:00'
    three = 'TH', 'с 12:00 до 14:00'
    four = 'FR', 'с 14:00 до 16:00'
    five = 'FV', 'с 16:00 до 18:00'
    six = 'SX', 'с 18:00 до 20:00'


class Order(TimeStampedModel):
    client = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='client_orders',
        verbose_name='Клиент',
    )
    client_name = models.CharField(
        max_length=80,
        verbose_name='Имя клиента',
        db_index=True,
    )
    bouquet = models.ForeignKey(
        Bouquet,
        on_delete=models.PROTECT,
        verbose_name='Букет'
    )
    price = models.DecimalField(
        max_digits=9,
        decimal_places=2,
        verbose_name='Сумма',
    )
    delivery_time = models.CharField(
        max_length=17,
        verbose_name='Интервал доставки',
        choices=IntervalOrder.choices,
        default=IntervalOrder.first,
        db_index=True
    )
    address = models.CharField(
        max_length=300,
        verbose_name='Адрес',
    )
    phone = PhoneNumberField(
        verbose_name='Номер телефона',
    )
    status = models.CharField(
        max_length=2,
        verbose_name='Статус заказа',
        choices=StatusOrder.choices,
        default=StatusOrder.unprocessed,
        db_index=True,
    )
    courier = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='courier_orders',
        verbose_name='Курьер',
    )
    florist = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='florist_orders',
        verbose_name='Флорист',
    )
    paid = models.BooleanField(
        'Оплачен',
        default=False,
    )

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return str(self.id)

flower_workshop/orders/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt

from bouquets.models import Bouquet
from orders.models import Order
from django.utils.timezone import localtime, timedelta


@csrf_exempt
def create_order(request):
    return render(request, 'orders/order.html')


@csrf_exempt
def order_step(request):
    bouquet = get_object_or_404(Bouquet, pk=request.POST.get('bouquet_id'))
    params = {
        'client_name': request.POST.get('client_name'),
        'bouquet': bouquet,
        'price': bouquet.price,
        'delivery_time': request.POST.get('orderTime'),
        'address': request.POST.get('adres'),
        'phone': request.POST.get('tel'),
        'paid': False,
    }
    order = Order.objects.filter(**params).last()
    if order and order.created <= localtime() - timedelta(minutes=5) or not order:
        order = Order.objects.create(**params)
    return render(
        request,
        'orders/order-step.html',
        context={
            'bouquet': bouquet,
            'order': order,
        }
    )


def my_order(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.paid = True
    order.save()
    bouquet = order.bouquet
    return render(
        request,
        'orders/my_order.html',
        context={
            'bouquet': bouquet,
            'order': order,
        }
    )

flower_workshop/templates/orders/my_order.html
{% extends 'base.html' %}
{% load static humanize %}
{% block title %}{{ bouquet.name }}{% endblock %}
{% block content %}
    <section id="card">
        <div class="container">
            <div class="card ficb">
                <div class="card__block card__block_first">
                    <img src="{{ bouquet.image.url }}" alt="{{ bouquet.name }}" class="card__img">
                </div>
                <div class="card__block card__block_sec">
                    <div class="title">✓ Заказ успешно оплачен</div>
                    <div class="title">{{ bouquet.name }}</div>
                    <div class="card__block_price">{{ bouquet.price|floatformat|intcomma }} руб</div>
                    <div class="card__elems ">
                        <span class="card__elems_intro">Состав</span>
                        <div class="card__items">
                            {% for bouquet_flower in bouquet.flowers.all %}
                                <span class="card_items_intro">
                                    {{ bouquet_flower.flower }} - {{ bouquet_flower.quantity }} шт.
                                </span>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="card__elems ">
                        <span class="card__elems_intro">Номер закзаза: <br><b>{{ order.pk }}</b></span>
                    </div>
                    <div class="card__elems ">
                        <span class="card__elems_intro">Время доставки: <br><b>{{ order.get_delivery_time_display }}</b></span>
                    </div>
                    <div class="card__elems ">
                        <span class="card__elems_intro">Статус: <br><b>{{ order.get_status_display }}</b></span>
                    </div>
                    <button class="btn largeBtn card__btn" onclick='goto(`{% url 'bouquets:catalog' %}`)'>
                        Посмотреть что есть ещё
                    </button>
                </div>
            </div>
        </div>
    </section>
    <section id="consultation">
        <div class="container">
            <div class="consultation">
                <div class="title consultation__title">Оставьте заявку на консультацию</div>
                {% include 'consultation/components/consultation_form.html' %}
            </div>
        </div>
    </section>
{% endblock content %}

flower_workshop/templates/orders/order-step.html
{% extends 'base.html' %}
{% load static humanize %}
{% block title %}Оплата{% endblock %}
{% block content %}
	<section id="orderStep">
		<div class="container">
			<div class="order orderStep">
				<div class="order__block">
					<div class="order_items">
						<div class="title">Оплата</div>
						<form action="{% url 'my_order' pk=order.pk %}" class="order__form orderStep_form">
							<div class="order__form_block">
								<div class="order__form_items">
									<div class="order__form_intro">номер карты</div>
									<input type="text" name="cardNum" class="order__form_input orderStep_form_input" placeholder="Введите номер" required>
									<div class="order__form_item fic">
										<input type="text" name="cardMm" class="order__form_input orderStep_form_input" placeholder="ММ" required>
										<input type="text" name="cardGg" class="order__form_input orderStep_form_input" placeholder="ГГ" required>
									</div>
									
									<input type="text" name="cardFname" class="order__form_input orderStep_form_input" placeholder="Имя владельца" required>
									<input type="text" name="cardCvc" class="order__form_input orderStep_form_input" placeholder="CVC" required>
								</div>
								<div class="order__form_items">
									<div class="order__form_intro">Ваш e-mail (необязательно)</div>
									<input type="email" name="mail" class="order__form_input orderStep_form_input" placeholder="pochta@mail.ru">
								</div>
							</div>
							<div class="order__form_line"></div>
							<div class="order__form_btns ficb">
								<button class="btn order__form_pay">Оплатить {{ bouquet.price|floatformat|intcomma }} руб</button>
								<button class="btn order__form_btn"  onclick="history.back()">Назад</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
		<img src="{% static 'img/orderImg.jpg' %}" alt="orderImg" class="order__img">
	</section>
{% endblock content %}

flower_workshop/templates/orders/order.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Подбор букета{% endblock %}
{% block content %}
	<section id="order">
		<div class="container">
			<div class="order">
				<div class="order__block">
					<div class="order_items">
						<div class="title">Оформление доставки</div>
						<form action="{% url "order-step"%}" class="order__form" method="POST">
							<div class="order__form_block ficb">
								<input type="text" name="client_name" class="order__form_input" placeholder="Введите Имя" required>
								<input id="order_phone_input" type="text" name="tel" class="order__form_input" placeholder="+ 7 (999) 000 00 00" required>
								<input type="text" name="adres" class="order__form_input" placeholder="Адрес доставки" required>
                                <input type="hidden" name="bouquet_id" value="{{ request.GET.bouquet_id }}" class="order__form_input" placeholder="Адрес доставки">
							</div>
							<div class="order__form_btns fic">
								<div class="order__form_radioBlock ">
									<input type="radio" name="orderTime" id="radio1" value="FRS" class="order__form_radio" />
									<label for="radio1" class="radioLable">Как можно скорее</label>
								</div>
								<div class="order__form_radioBlock">
									<input type="radio" name="orderTime" id="radio2" value="TW" class="order__form_radio" />
									<label for="radio2" class="radioLable">с 10:00 до 12:00</label>
								</div>
								<div class="order__form_radioBlock">
									<input type="radio" name="orderTime" id="radio3" value="TH" class="order__form_radio" />
									<label for="radio3" class="radioLable">с 12:00 до 14:00</label>
								</div>
								<div class="order__form_radioBlock">
									<input type="radio" name="orderTime" id="radio4" value="FR" class="order__form_radio" />
									<label for="radio4" class="radioLable">с 14:00 до 16:00</label>
								</div>
								<div class="order__form_radioBlock">
									<input type="radio" name="orderTime" id="radio5" value="FV" class="order__form_radio" />
									<label for="radio5" class="radioLable">с 16:00 до 18:00</label>
								</div>
								<div class="order__form_radioBlock">
									<input type="radio" name="orderTime" id="radio6" value="SX" class="order__form_radio" />
									<label for="radio6" class="radioLable">с 18:00 до 20:00</label>
								</div>
								
							</div>
							<div class="order__form_line"></div>
							<div class="order__form_btns ficb">
								<button class="btn order__form_pay">Оплатить</button>
								<button class="btn order__form_btn" onclick="history.back()">Назад</button>
							</div>
						</form>
					</div>
					
				</div>
			</div>
		</div>
		<img src="{% static 'img/orderImg.jpg' %}" alt="orderImg" class="order__img">
	</section>
	<script>
		document.querySelector('input[type=radio]').onclick = function(e) {
			// e.preventDefault()
			// console.log(e.target)
			console.log(e.target.value)
		}
        IMask(
            document.getElementById('order_phone_input'),
            {mask: '+{7} (000) 000-00-00'}
        );
	</script>
{% endblock content %}